### ISSUE TITLE
File Exporter Not Working

### ISSUE THREAD

**Issue by arTECRAD** [Vaida12345/Annotation#1]
The file export and file import features are not working. I fixed the issue by duplicating the .fileExporter method from where it was originally declared in the CommandGroup to an outside scope just beneath the onAppear so that it was declared in the ContentView(). I'm running MacOS Ventura, but don't think this is an OS issue.

**Comment by Vaida12345** [comment]
It is working fine on my computer. But I'm fixing it with your solution anyway
